import Head from "next/head";
import Navigation from "../components/a-navigation/Navigation";
import Home from "../components/b-home/Home";
import Portfolio from "../components/c-portfolio/Portfolio";
import Skills from "../components/d-skills/Skills";

const HomePage = ({ projects }) => {
  return (
    <>
      <Head>
        <title>Mark Christian Albinto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <Home />
      <Portfolio projects={projects} />
      <Skills />
    </>
  );
};

export const getStaticProps = async () => {
  const res = await fetch(`http://localhost:3000/api/projects`);
  const projects = await res.json();

  return {
    props: {
      projects,
    },
  };
};

export default HomePage;
