import Head from "next/head";
import Navigation from "../components/a-navigation/Navigation";
import Home from "../components/b-home/Home";
import Portfolio from "../components/c-portfolio/Portfolio";
import Skills from "../components/d-skills/Skills";
import projectsData from "../../data/projects.json";

const HomePage = ({ projects, projectsTabs }) => {
  return (
    <>
      <Head>
        <title>Mark Christian Albinto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <Home />
      <Portfolio projects={projects} projectsTabs={projectsTabs} />
      <Skills />
    </>
  );
};

export const getStaticProps = async (context) => {
  // const projects = projectsData;

  let apiURL;

  if (process.env.NODE_ENV === "production") {
    apiURL = process.env.BASE_URL_PRODUCTION;
  } else {
    apiURL = process.env.BASE_URL_DEVELOPMENT;
  }
  console.log(apiURL);

  const res = await fetch(`${apiURL}/api/projects`);
  const projects = await res.json();

  const projectsTabs = [...new Set(projects.map((project) => project.type.toLowerCase()))];
  console.log(projectsTabs);

  return {
    props: {
      projects,
      projectsTabs,
    },
  };
};

export default HomePage;
